// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: 'OSU CS Courses',
      description: 'A comprehensive guide to Oregon State University\'s computer science courses',
      social: {
        github: 'https://github.com/derekrgreene/osu-cs-courses.com',
      },
      sidebar: [
        {
          label: 'Getting Started',
          items: [
            { label: 'Home', slug: '' },
          ],
        },
        {
          label: 'Courses',
          items: [
            { label: 'Overview', slug: 'courses' },
            {
              label: 'Core Courses',
              items: [
                
                { label: 'CS 162', slug: 'courses/core/cs162' },
                { label: 'CS 162H', slug: 'courses/core/cs162h' },
                { label: 'CS 225', slug: 'courses/core/cs225' },
                { label: 'CS 261', slug: 'courses/core/cs261' },
                { label: 'CS 271', slug: 'courses/core/cs271' },
                { label: 'CS 290', slug: 'courses/core/cs290' },
                { label: 'CS 325', slug: 'courses/core/cs325' },
                { label: 'CS 325H', slug: 'courses/core/cs325h' },
                { label: 'CS 340', slug: 'courses/core/cs340' },
                { label: 'CS 361', slug: 'courses/core/cs361' },
                { label: 'CS 362', slug: 'courses/core/cs362' },
                { label: 'CS 362H', slug: 'courses/core/cs362h' },
                { label: 'CS 374', slug: 'courses/core/cs374' },
                { label: 'CS 391', slug: 'courses/core/cs391' },
                { label: 'CS 391H', slug: 'courses/core/cs391h' },
                { label: 'MTH 231', slug: 'courses/core/mth231' },
                { label: 'ENGR 100', slug: 'courses/core/engr100' },
                { label: 'ENGR 102', slug: 'courses/core/engr102' },
                { label: 'ENGR 103', slug: 'courses/core/engr103' },
              ],
            },
            { label: 'Electives',
              items: [

                { label: 'CS 101', slug: 'courses/electives/cs101' },
                { label: 'CS 161', slug: 'courses/electives/cs161' },
                { label: 'CS 175', slug: 'courses/electives/cs175' },
                { label: 'CS 199', slug: 'courses/electives/cs199' },
                { label: 'CS 274', slug: 'courses/electives/cs274' },
                { label: 'CS 299', slug: 'courses/electives/cs299' },
                { label: 'CS 312', slug: 'courses/electives/cs312' },
                { label: 'CS 321', slug: 'courses/electives/cs321' },
                { label: 'CS 321H', slug: 'courses/electives/cs321h' },
                { label: 'CS 331', slug: 'courses/electives/cs331' },
                { label: 'CS 331H', slug: 'courses/electives/cs331h' },
                { label: 'CS 332', slug: 'courses/electives/cs332' },
                { label: 'CS 352', slug: 'courses/electives/cs352' },
                { label: 'CS 370', slug: 'courses/electives/cs370' },
                { label: 'CS 372', slug: 'courses/electives/cs372' },
                { label: 'CS 373', slug: 'courses/electives/cs373' },
                { label: 'CS 381', slug: 'courses/electives/cs381' },
                { label: 'CS 399', slug: 'courses/electives/cs399' },
                { label: 'CS 401', slug: 'courses/electives/cs401' },
                { label: 'CS 403', slug: 'courses/electives/cs403' },
                { label: 'CS 404', slug: 'courses/electives/cs404' },
                { label: 'CS 405', slug: 'courses/electives/cs405' },
                { label: 'CS 406', slug: 'courses/electives/cs406' },
                { label: 'CS 407', slug: 'courses/electives/cs407' },
                { label: 'CS 407H', slug: 'courses/electives/cs407h' },
                { label: 'CS 410', slug: 'courses/electives/cs410' },
                { label: 'CS 419', slug: 'courses/electives/cs419' },
                { label: 'CS 419H', slug: 'courses/electives/cs419h' },
                { label: 'CS 420', slug: 'courses/electives/cs420' },
                { label: 'CS 424', slug: 'courses/electives/cs424' },
                { label: 'CS 425', slug: 'courses/electives/cs425' },
                { label: 'CS 426', slug: 'courses/electives/cs426' },
                { label: 'CS 427', slug: 'courses/electives/cs427' },
                { label: 'CS 428', slug: 'courses/electives/cs428' },
                { label: 'CS 432', slug: 'courses/electives/cs432' },
                { label: 'CS 434', slug: 'courses/electives/cs434' },
                { label: 'CS 434H', slug: 'courses/electives/cs434h' },
                { label: 'CS 440', slug: 'courses/electives/cs440' },
                { label: 'CS 444', slug: 'courses/electives/cs444' },
                { label: 'CS 446', slug: 'courses/electives/cs446' },
                { label: 'CS 450', slug: 'courses/electives/cs450' },
                { label: 'CS 453', slug: 'courses/electives/cs453' },
                { label: 'CS 457', slug: 'courses/electives/cs457' },
                { label: 'CS 458', slug: 'courses/electives/cs458' },
                { label: 'CS 461', slug: 'courses/electives/cs461' },
                { label: 'CS 462', slug: 'courses/electives/cs462' },
                { label: 'CS 463', slug: 'courses/electives/cs463' },
                { label: 'CS 464', slug: 'courses/electives/cs464' },
                { label: 'CS 466', slug: 'courses/electives/cs466' },
                { label: 'CS 467', slug: 'courses/electives/cs467' },
                { label: 'CS 468', slug: 'courses/electives/cs468' },
                { label: 'CS 469', slug: 'courses/electives/cs469' },
                { label: 'CS 472', slug: 'courses/electives/cs472' },
                { label: 'CS 473', slug: 'courses/electives/cs473' },
                { label: 'CS 474', slug: 'courses/electives/cs474' },
                { label: 'CS 475', slug: 'courses/electives/cs475' },
                { label: 'CS 476', slug: 'courses/electives/cs476' },
                { label: 'CS 478', slug: 'courses/electives/cs478' },
                { label: 'CS 480', slug: 'courses/electives/cs480' },
                { label: 'CS 491', slug: 'courses/electives/cs491' },
                { label: 'CS 492', slug: 'courses/electives/cs492' },
                { label: 'CS 493', slug: 'courses/electives/cs493' },
                { label: 'CS 494', slug: 'courses/electives/cs494' },
                { label: 'CS 499', slug: 'courses/electives/cs499' },
                { label: 'ECE 271', slug: 'courses/electives/ece271' },
                { label: 'ECE 272', slug: 'courses/electives/ece272' },
                { label: 'ECE 375', slug: 'courses/electives/ece375' },
                { label: 'ST 314', slug: 'courses/electives/st314' },

            ],
            },
          ],
        },
        {
          label: 'Planning',
          items: [
            { label: 'Degree Roadmaps', slug: 'roadmaps' },
          ],
        },
        {
          label: 'Resources',
          items: [
            { label: 'Study Materials', slug: 'resources' },
          ],
        },
        {
          label: 'Community',
          items: [
            { label: 'Discussion', slug: 'community' },
          ],
        },
      ],
    }),
  ],
  // Set the site URL for production
  // site: 'https://osu-cs-courses.com',
});